/** Sjednocení názvů klubů z API-Football, ESPN, historie a ručních konfigurací. */
const ALIASES: Record<string, string> = {
  Sigma: 'Olomouc',
  'Sigma Olomouc': 'Olomouc',
  'SK Sigma Olomouc': 'Olomouc',
  Bolka: 'Boleslav',
  'Mlada Boleslav': 'Boleslav',
  'Mladá Boleslav': 'Boleslav',
  'FK Mladá Boleslav': 'Boleslav',
  Ostrava: 'Baník',
  'Baník Ostrava': 'Baník',
  'Banik Ostrava': 'Baník',
  'FC Baník Ostrava': 'Baník',
  'Jabl*nec': 'Jablonec',
  'FK Jablonec': 'Jablonec',
  'Sparta Praha': 'Sparta',
  'AC Sparta Prague': 'Sparta',
  'AC Sparta Praha': 'Sparta',
  'Sparta Prague': 'Sparta',
  'Slavia Praha': 'Slavia',
  'SK Slavia Prague': 'Slavia',
  'SK Slavia Praha': 'Slavia',
  'Slavia Prague': 'Slavia',
  'Viktoria Plzen': 'Plzeň',
  'Viktoria Plzeň': 'Plzeň',
  'FC Viktoria Plzeň': 'Plzeň',
  'FC Slovan Liberec': 'Liberec',
  'Slovan Liberec': 'Liberec',
  Karvina: 'Karviná',
  'MFK Karvina': 'Karviná',
  'MFK Karviná': 'Karviná',
  'Hradec Kralove': 'Hradec Králové',
  'FC Hradec Kralove': 'Hradec Králové',
  'FC Hradec Králové': 'Hradec Králové',
  'FK Pardubice': 'Pardubice',
  Zlin: 'Zlín',
  'FC Fastav Zlin': 'Zlín',
  'FC Zlín': 'Zlín',
  'FK Teplice': 'Teplice',
  'Bohemians 1905': 'Bohemians',
  'Bohemians Praha 1905': 'Bohemians',
  Slovacko: 'Slovácko',
  '1. FC Slovacko': 'Slovácko',
  '1. FC Slovácko': 'Slovácko',
  'FC Zbrojovka Brno': 'Zbrojovka Brno',
  'Zbrojovka Brno': 'Zbrojovka Brno',
  'Real Madrid CF': 'Real Madrid',
  'FC Barcelona': 'Barcelona',
  'Paris Saint-Germain': 'PSG',
  'Paris Saint Germain': 'PSG',
  'FC Bayern Munich': 'Bayern Mnichov',
  'Bayern Munich': 'Bayern Mnichov',
  Internazionale: 'Inter Milán',
  'Inter Milan': 'Inter Milán',
  'AC Milan': 'AC Milán',
  'Atletico Madrid': 'Atlético Madrid',
  'Borussia Dortmund': 'Dortmund',
  'Manchester City': 'Manchester City',
  'Manchester United': 'Manchester United',
};

export function canonTeam(name: string): string {
  const t = (name ?? '').trim();
  return ALIASES[t] ?? t;
}
