/** Sjednocení názvů klubů z veřejných zdrojů, ESPN, historie a ručních konfigurací. */
const ALIASES: Record<string, string> = {
  Sigma: 'Olomouc',
  'Sigma Olomouc': 'Olomouc',
  'SK Sigma Olomouc': 'Olomouc',
  Bolka: 'Boleslav',
  'Mlada Boleslav': 'Boleslav',
  'Mladá Boleslav': 'Boleslav',
  'FK Mladá Boleslav': 'Boleslav',
  Ostrava: 'Baník',
  'Baník Ostrava': 'Baník',
  'Banik Ostrava': 'Baník',
  'FC Baník Ostrava': 'Baník',
  'FC Banik Ostrava': 'Baník',
  'Jabl*nec': 'Jablonec',
  'FK Jablonec': 'Jablonec',
  'Sparta Praha': 'Sparta',
  'AC Sparta Prague': 'Sparta',
  'AC Sparta Praha': 'Sparta',
  'Sparta Prague': 'Sparta',
  'Slavia Praha': 'Slavia',
  'SK Slavia Prague': 'Slavia',
  'SK Slavia Praha': 'Slavia',
  'Slavia Prague': 'Slavia',
  'Viktoria Plzen': 'Plzeň',
  'Viktoria Plzeň': 'Plzeň',
  'FC Viktoria Plzeň': 'Plzeň',
  'FC Viktoria Plzen': 'Plzeň',
  'FC Slovan Liberec': 'Liberec',
  'Slovan Liberec': 'Liberec',
  Karvina: 'Karviná',
  'MFK Karvina': 'Karviná',
  'MFK Karviná': 'Karviná',
  'Hradec Kralove': 'Hradec Králové',
  'FC Hradec Kralove': 'Hradec Králové',
  'FC Hradec Králové': 'Hradec Králové',
  'FK Pardubice': 'Pardubice',
  'FK Dukla Praha': 'Dukla',
  'Dukla Praha': 'Dukla',
  'Dukla Prague': 'Dukla',
  Zlin: 'Zlín',
  'FC Fastav Zlin': 'Zlín',
  'FC Zlín': 'Zlín',
  'FK Teplice': 'Teplice',
  'Bohemians 1905': 'Bohemians',
  'Bohemians Praha 1905': 'Bohemians',
  Slovacko: 'Slovácko',
  '1. FC Slovacko': 'Slovácko',
  '1.FC Slovacko': 'Slovácko',
  '1.FC Slovácko': 'Slovácko',
  '1. FC Slovácko': 'Slovácko',
  'FC Zbrojovka Brno': 'Zbrojovka Brno',
  'SK Artis Brno': 'Artis Brno',
  'Zbrojovka Brno': 'Zbrojovka Brno',
  'Real Madrid CF': 'Real Madrid',
  'FC Barcelona': 'Barcelona',
  'Paris Saint-Germain': 'PSG',
  'Paris Saint Germain': 'PSG',
  'FC Bayern Munich': 'Bayern Mnichov',
  'Bayern München': 'Bayern Mnichov',
  'FC Bayern München': 'Bayern Mnichov',
  'Bayern Munich': 'Bayern Mnichov',
  Internazionale: 'Inter Milán',
  Inter: 'Inter Milán',
  'Inter Milan': 'Inter Milán',
  'AC Milan': 'AC Milán',
  Milan: 'AC Milán',
  'Atletico Madrid': 'Atlético Madrid',
  'Atlético de Madrid': 'Atlético Madrid',
  'Borussia Dortmund': 'Dortmund',
  'Borussia Dortmund GmbH & Co. KGaA': 'Dortmund',
  'Manchester City': 'Manchester City',
  'Manchester United': 'Manchester United',
  'SSC Napoli': 'Neapol',
  Napoli: 'Neapol',
  'SL Benfica': 'Benfica',
  'FC Porto': 'Porto',
  'Sporting Lisbon': 'Sporting CP',
  'Sporting Clube de Portugal': 'Sporting CP',
  'RC Celta de Vigo': 'Celta Vigo',
  Celta: 'Celta Vigo',
  'SC Freiburg': 'Freiburg',
  'Nottingham Forest FC': 'Nottingham Forest',
  'AEK Athens': 'AEK Athény',
  'AEK Athens FC': 'AEK Athény',
  Strasbourg: 'Štrasburk',
  'RC Strasbourg Alsace': 'Štrasburk',
  'Shakhtar Donetsk': 'Šachtar Doněck',
  'FC Shakhtar Donetsk': 'Šachtar Doněck',
  '1. FSV Mainz 05': 'Mainz',
  'FSV Mainz 05': 'Mainz',
  'AZ Alkmaar': 'AZ Alkmaar',
  'Rayo Vallecano de Madrid': 'Rayo Vallecano',
  'AFC Ajax': 'Ajax',
  'Ajax Amsterdam': 'Ajax',
  'Celtic FC': 'Celtic',
  'Rangers FC': 'Rangers',
  'Fenerbahce': 'Fenerbahçe',
  'Fenerbahçe SK': 'Fenerbahçe',
  'Feyenoord Rotterdam': 'Feyenoord',
  'Club Brugge KV': 'Club Brugge',
  'Red Bull Salzburg': 'Salzburg',
  'FC Salzburg': 'Salzburg',
  'Red Star Belgrade': 'Crvena zvezda',
  'Crvena Zvezda': 'Crvena zvezda',
  'FK Crvena Zvezda': 'Crvena zvezda',
  'F.C. Copenhagen': 'Copenhagen',
  'FC Copenhagen': 'Copenhagen',
  'Ferencvaros': 'Ferencváros',
  'Ferencvárosi TC': 'Ferencváros',
  'Panathinaikos FC': 'Panathinaikos',
  'Dynamo Kyiv': 'Dynamo Kyjev',
  'FC Dynamo Kyiv': 'Dynamo Kyjev',
  'FC Basel 1893': 'Basel',
  'Malmo FF': 'Malmö',
  'Malmö FF': 'Malmö',
  'SK Slovan Bratislava': 'Slovan Bratislava',
  'ŠK Slovan Bratislava': 'Slovan Bratislava',
  'SK Sturm Graz': 'Sturm Graz',
  'OGC Nice': 'Nice',
  'RSC Anderlecht': 'Anderlecht',
  'Besiktas': 'Beşiktaş',
  'Besiktas JK': 'Beşiktaş',
  'Beşiktaş JK': 'Beşiktaş',
  'KAA Gent': 'Gent',
  'FK Austria Wien': 'Austria Wien',
  'Austria Vienna': 'Austria Wien',
  'Istanbul Basaksehir': 'Başakşehir',
  'İstanbul Başakşehir FK': 'Başakşehir',
  'SK Rapid Wien': 'Rapid Vídeň',
  'Rapid Vienna': 'Rapid Vídeň',
  'PAOK Thessaloniki': 'PAOK',
  'PAOK FC': 'PAOK',
  'GNK Dinamo Zagreb': 'Dinamo Zagreb',
  'Bohemian FC': 'Bohemians Dublin',
};

export function canonTeam(name: string): string {
  const t = (name ?? '').trim();
  return ALIASES[t] ?? t;
}
